test:
  image: joajfreitas/arch-python
  stage: build
  needs: []
  tags:
    - docker

  script:
    - pytest -v fcp



install:
  image: joajfreitas/arch-python
  stage: build
  needs: []
  tags:
    - docker

  script:
    - python3 setup.py install
    - fcp --version

release:
  image: joajfreitas/arch-python
  stage: deploy
  only:
    - release

  script:
    - python setup.py sdist
    - pip install twine
    - twine upload -u joajfreitas -p $PYPI_PASSWORD dist/* 


pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - release-notes
    expire_in: 1 day
