build-pic:
  image: archlinux
  stage: build
  needs: []
  tags:
    - docker

  script:
    - pacman -S python --nocofirm
    - python3 -V
    - pip3 install setuptools
    - pip3 install markdown
    - python3 setup.py install
    - fcp --version
