test:
  image: joajfreitas/arch-python
  stage: build
  needs: []
  tags:
    - docker

  script:
    - pytest -v fcp



install:
  image: arch-python
  stage: build
  needs: []
  tags:
    - docker

  script:
    - python3 setup.py install
    - fcp --version

release:
  image: joajfreitas/arch-python
  only:
    - release

  script:
    - python setup.py install
    - pip install twine
    - twine upload -u joajfreitas -p $PYPI_PASSWRD /* 
