test:
  image: joajfreitas/arch-python
  stage: build
  needs: []
  tags:
    - docker

  script:
    - pip3 install pytest
    - cd fcp && pytest -v



install:
  image: archlinux
  stage: build
  needs: []
  tags:
    - docker

  script:
    - pacman -Syu --noconfirm
    - pacman -S python python-pip libglvnd --noconfirm
    - python3 -V
    - pip3 install setuptools
    - pip3 install markdown
    - python3 setup.py install
    - fcp --version
