/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.8 Sun Oct  6 13:13:56 2024.
 */

#include <string.h>

#include "example.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int example_pedals_pack(
    uint8_t *dst_p,
    const struct example_pedals_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->acc_pos, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->brak_pos, 0u, 0xffu);

    return (2);
}

int example_pedals_unpack(
    struct example_pedals_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->acc_pos = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brak_pos = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int example_pedals_init(struct example_pedals_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct example_pedals_t));

    return 0;
}

uint8_t example_pedals_acc_pos_encode(double value)
{
    return (uint8_t)(value);
}

double example_pedals_acc_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool example_pedals_acc_pos_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t example_pedals_brak_pos_encode(double value)
{
    return (uint8_t)(value);
}

double example_pedals_brak_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool example_pedals_brak_pos_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int example_cell_voltage_pack(
    uint8_t *dst_p,
    const struct example_cell_voltage_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->mux, 0u, 0xffu);

    switch (src_p->mux) {

    case 0:
        dst_p[1] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
        break;

    case 2:
        dst_p[1] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
        break;

    case 3:
        dst_p[1] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
        break;

    default:
        break;
    }

    return (3);
}

int example_cell_voltage_unpack(
    struct example_cell_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->mux = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->mux) {

    case 0:
        dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        break;

    case 1:
        dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        break;

    case 2:
        dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        break;

    case 3:
        dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
        dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int example_cell_voltage_init(struct example_cell_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct example_cell_voltage_t));

    return 0;
}

uint8_t example_cell_voltage_mux_encode(double value)
{
    return (uint8_t)(value);
}

double example_cell_voltage_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool example_cell_voltage_mux_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t example_cell_voltage_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double example_cell_voltage_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool example_cell_voltage_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
