/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.8 Sun Oct  6 13:13:56 2024.
 */

#ifndef EXAMPLE_H
#define EXAMPLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define EXAMPLE_PEDALS_FRAME_ID (0x0au)
#define EXAMPLE_CELL_VOLTAGE_FRAME_ID (0x0bu)

/* Frame lengths in bytes. */
#define EXAMPLE_PEDALS_LENGTH (2u)
#define EXAMPLE_CELL_VOLTAGE_LENGTH (3u)

/* Extended or standard frame types. */
#define EXAMPLE_PEDALS_IS_EXTENDED (0)
#define EXAMPLE_CELL_VOLTAGE_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define EXAMPLE_PEDALS_NAME "Pedals"
#define EXAMPLE_CELL_VOLTAGE_NAME "CellVoltage"

/* Signal Names. */
#define EXAMPLE_PEDALS_ACC_POS_NAME "acc_pos"
#define EXAMPLE_PEDALS_BRAK_POS_NAME "brak_pos"
#define EXAMPLE_CELL_VOLTAGE_MUX_NAME "mux"
#define EXAMPLE_CELL_VOLTAGE_VOLTAGE_NAME "voltage"

/**
 * Signals in message Pedals.
 *
 * All signal values are as on the CAN bus.
 */
struct example_pedals_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t acc_pos;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t brak_pos;
};

/**
 * Signals in message CellVoltage.
 *
 * All signal values are as on the CAN bus.
 */
struct example_cell_voltage_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t mux;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t voltage;
};

/**
 * Pack message Pedals.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int example_pedals_pack(
    uint8_t *dst_p,
    const struct example_pedals_t *src_p,
    size_t size);

/**
 * Unpack message Pedals.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int example_pedals_unpack(
    struct example_pedals_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Pedals.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int example_pedals_init(struct example_pedals_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t example_pedals_acc_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double example_pedals_acc_pos_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool example_pedals_acc_pos_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t example_pedals_brak_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double example_pedals_brak_pos_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool example_pedals_brak_pos_is_in_range(uint8_t value);

/**
 * Pack message CellVoltage.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int example_cell_voltage_pack(
    uint8_t *dst_p,
    const struct example_cell_voltage_t *src_p,
    size_t size);

/**
 * Unpack message CellVoltage.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int example_cell_voltage_unpack(
    struct example_cell_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CellVoltage.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int example_cell_voltage_init(struct example_cell_voltage_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t example_cell_voltage_mux_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double example_cell_voltage_mux_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool example_cell_voltage_mux_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t example_cell_voltage_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double example_cell_voltage_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool example_cell_voltage_voltage_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
