/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 11
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_version = 1,
  anon_sym_COLON = 2,
  anon_sym_struct = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_AT = 6,
  anon_sym_COMMA = 7,
  anon_sym_PIPE = 8,
  sym_base_type = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_Optional = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_enum = 15,
  anon_sym_EQ = 16,
  anon_sym_impl = 17,
  anon_sym_for = 18,
  anon_sym_signal = 19,
  anon_sym_service = 20,
  anon_sym_method = 21,
  anon_sym_returns = 22,
  anon_sym_device = 23,
  anon_sym_mod = 24,
  anon_sym_SEMI = 25,
  sym_identifier = 26,
  sym_string = 27,
  sym_number = 28,
  sym_comment = 29,
  sym_source_file = 30,
  sym_preamble = 31,
  sym_struct = 32,
  sym_struct_field = 33,
  sym_type = 34,
  sym_array_type = 35,
  sym_dynamic_array_type = 36,
  sym_optional_type = 37,
  sym_param = 38,
  sym_param_argument = 39,
  sym_enum_block = 40,
  sym_enum_field = 41,
  sym_impl = 42,
  sym_extension_field = 43,
  sym_signal_block = 44,
  sym_service = 45,
  sym_method = 46,
  sym_device = 47,
  sym_device_field = 48,
  sym_device_field_name = 49,
  sym_mod_expr = 50,
  sym__mod_name = 51,
  sym_value = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_struct_repeat1 = 54,
  aux_sym_struct_field_repeat1 = 55,
  aux_sym_param_repeat1 = 56,
  aux_sym_enum_block_repeat1 = 57,
  aux_sym_impl_repeat1 = 58,
  aux_sym_signal_block_repeat1 = 59,
  aux_sym_service_repeat1 = 60,
  aux_sym_device_repeat1 = 61,
  alias_sym_composed_type = 62,
  alias_sym_enum_field_name = 63,
  alias_sym_enum_name = 64,
  alias_sym_method_input_type = 65,
  alias_sym_method_name = 66,
  alias_sym_method_output_type = 67,
  alias_sym_mod_name = 68,
  alias_sym_param_name = 69,
  alias_sym_service_name = 70,
  alias_sym_struct_field_name = 71,
  alias_sym_struct_name = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_version] = "version",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE] = "|",
  [sym_base_type] = "base_type",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_Optional] = "Optional",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_enum] = "enum",
  [anon_sym_EQ] = "=",
  [anon_sym_impl] = "impl",
  [anon_sym_for] = "for",
  [anon_sym_signal] = "signal",
  [anon_sym_service] = "service",
  [anon_sym_method] = "method",
  [anon_sym_returns] = "returns",
  [anon_sym_device] = "device",
  [anon_sym_mod] = "mod",
  [anon_sym_SEMI] = ";",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_struct] = "struct",
  [sym_struct_field] = "struct_field",
  [sym_type] = "type",
  [sym_array_type] = "array_type",
  [sym_dynamic_array_type] = "dynamic_array_type",
  [sym_optional_type] = "optional_type",
  [sym_param] = "param",
  [sym_param_argument] = "param_argument",
  [sym_enum_block] = "enum_block",
  [sym_enum_field] = "enum_field",
  [sym_impl] = "impl",
  [sym_extension_field] = "extension_field",
  [sym_signal_block] = "signal_block",
  [sym_service] = "service",
  [sym_method] = "method",
  [sym_device] = "device",
  [sym_device_field] = "device_field",
  [sym_device_field_name] = "device_field_name",
  [sym_mod_expr] = "mod_expr",
  [sym__mod_name] = "_mod_name",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_struct_field_repeat1] = "struct_field_repeat1",
  [aux_sym_param_repeat1] = "param_repeat1",
  [aux_sym_enum_block_repeat1] = "enum_block_repeat1",
  [aux_sym_impl_repeat1] = "impl_repeat1",
  [aux_sym_signal_block_repeat1] = "signal_block_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
  [aux_sym_device_repeat1] = "device_repeat1",
  [alias_sym_composed_type] = "composed_type",
  [alias_sym_enum_field_name] = "enum_field_name",
  [alias_sym_enum_name] = "enum_name",
  [alias_sym_method_input_type] = "method_input_type",
  [alias_sym_method_name] = "method_name",
  [alias_sym_method_output_type] = "method_output_type",
  [alias_sym_mod_name] = "mod_name",
  [alias_sym_param_name] = "param_name",
  [alias_sym_service_name] = "service_name",
  [alias_sym_struct_field_name] = "struct_field_name",
  [alias_sym_struct_name] = "struct_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_base_type] = sym_base_type,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_Optional] = anon_sym_Optional,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_method] = anon_sym_method,
  [anon_sym_returns] = anon_sym_returns,
  [anon_sym_device] = anon_sym_device,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_struct] = sym_struct,
  [sym_struct_field] = sym_struct_field,
  [sym_type] = sym_type,
  [sym_array_type] = sym_array_type,
  [sym_dynamic_array_type] = sym_dynamic_array_type,
  [sym_optional_type] = sym_optional_type,
  [sym_param] = sym_param,
  [sym_param_argument] = sym_param_argument,
  [sym_enum_block] = sym_enum_block,
  [sym_enum_field] = sym_enum_field,
  [sym_impl] = sym_impl,
  [sym_extension_field] = sym_extension_field,
  [sym_signal_block] = sym_signal_block,
  [sym_service] = sym_service,
  [sym_method] = sym_method,
  [sym_device] = sym_device,
  [sym_device_field] = sym_device_field,
  [sym_device_field_name] = sym_device_field_name,
  [sym_mod_expr] = sym_mod_expr,
  [sym__mod_name] = sym__mod_name,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_struct_field_repeat1] = aux_sym_struct_field_repeat1,
  [aux_sym_param_repeat1] = aux_sym_param_repeat1,
  [aux_sym_enum_block_repeat1] = aux_sym_enum_block_repeat1,
  [aux_sym_impl_repeat1] = aux_sym_impl_repeat1,
  [aux_sym_signal_block_repeat1] = aux_sym_signal_block_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
  [aux_sym_device_repeat1] = aux_sym_device_repeat1,
  [alias_sym_composed_type] = alias_sym_composed_type,
  [alias_sym_enum_field_name] = alias_sym_enum_field_name,
  [alias_sym_enum_name] = alias_sym_enum_name,
  [alias_sym_method_input_type] = alias_sym_method_input_type,
  [alias_sym_method_name] = alias_sym_method_name,
  [alias_sym_method_output_type] = alias_sym_method_output_type,
  [alias_sym_mod_name] = alias_sym_mod_name,
  [alias_sym_param_name] = alias_sym_param_name,
  [alias_sym_service_name] = alias_sym_service_name,
  [alias_sym_struct_field_name] = alias_sym_struct_field_name,
  [alias_sym_struct_name] = alias_sym_struct_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_base_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_method] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_device] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_type] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_block] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_field] = {
    .visible = true,
    .named = true,
  },
  [sym_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_field] = {
    .visible = true,
    .named = true,
  },
  [sym_signal_block] = {
    .visible = true,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_device] = {
    .visible = true,
    .named = true,
  },
  [sym_device_field] = {
    .visible = true,
    .named = true,
  },
  [sym_device_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_mod_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__mod_name] = {
    .visible = false,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_impl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_signal_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_device_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_composed_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_enum_field_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_enum_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_method_input_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_method_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_method_output_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_mod_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_service_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_struct_field_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_struct_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_mod_name,
  },
  [2] = {
    [1] = alias_sym_struct_name,
  },
  [3] = {
    [1] = alias_sym_enum_name,
  },
  [4] = {
    [0] = alias_sym_enum_field_name,
  },
  [5] = {
    [1] = alias_sym_service_name,
  },
  [6] = {
    [0] = alias_sym_composed_type,
  },
  [7] = {
    [0] = alias_sym_struct_field_name,
  },
  [8] = {
    [0] = alias_sym_param_name,
  },
  [9] = {
    [1] = alias_sym_method_name,
    [3] = alias_sym_method_input_type,
    [8] = alias_sym_method_output_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 44,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 58,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 72,
  [114] = 114,
  [115] = 89,
  [116] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(72);
      ADVANCE_MAP(
        '"', 9,
        '(', 89,
        ')', 90,
        ',', 79,
        '/', 10,
        ':', 74,
        ';', 102,
        '=', 92,
        '@', 78,
        'O', 51,
        '[', 85,
      );
      if (lookahead == '\\') SKIP(71);
      if (lookahead == ']') ADVANCE(86);
      if (lookahead == 'd') ADVANCE(25);
      if (lookahead == 'e') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'i') ADVANCE(42);
      if (lookahead == 'm') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(69);
      if (lookahead == 'v') ADVANCE(31);
      if (lookahead == '{') ADVANCE(76);
      if (lookahead == '|') ADVANCE(80);
      if (lookahead == '}') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(14);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\r') ADVANCE(125);
      if (lookahead == '\\') ADVANCE(123);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '(') ADVANCE(89);
      if (lookahead == ')') ADVANCE(90);
      if (lookahead == ',') ADVANCE(79);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') SKIP(2);
      if (lookahead == ']') ADVANCE(86);
      if (lookahead == '|') ADVANCE(80);
      if (lookahead == '}') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(124);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(122);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == 'O') ADVANCE(116);
      if (lookahead == '[') ADVANCE(85);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == 'f') ADVANCE(104);
      if (lookahead == 'i') ADVANCE(118);
      if (lookahead == 'u') ADVANCE(118);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') SKIP(6);
      if (lookahead == 's') ADVANCE(110);
      if (lookahead == '}') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 15:
      if (lookahead == '2') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == '3') ADVANCE(15);
      if (lookahead == '6') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 17:
      if (lookahead == '4') ADVANCE(81);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(101);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(93);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(91);
      END_STATE();
    case 42:
      if (lookahead == 'm') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 51:
      if (lookahead == 'p') ADVANCE(60);
      END_STATE();
    case 52:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 66:
      if (lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 67:
      if (lookahead == 'v') ADVANCE(35);
      END_STATE();
    case 68:
      if (lookahead == 'v') ADVANCE(37);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 70:
      if (eof) ADVANCE(72);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 71:
      if (eof) ADVANCE(72);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_base_type);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_Optional);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_Optional);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_signal);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_signal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_method);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_device);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(103);
      if (lookahead == '6') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(125);
      if (lookahead == '\\') ADVANCE(123);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 8},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 8},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 8},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 8},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 8},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_base_type] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_Optional] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_method] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_device] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(100),
    [sym_preamble] = STATE(4),
    [anon_sym_version] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_service,
    ACTIONS(17), 1,
      anon_sym_device,
    ACTIONS(19), 1,
      anon_sym_mod,
    STATE(3), 7,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_device,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [34] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(26), 1,
      anon_sym_enum,
    ACTIONS(29), 1,
      anon_sym_impl,
    ACTIONS(32), 1,
      anon_sym_service,
    ACTIONS(35), 1,
      anon_sym_device,
    ACTIONS(38), 1,
      anon_sym_mod,
    STATE(3), 7,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_device,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [68] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_service,
    ACTIONS(17), 1,
      anon_sym_device,
    ACTIONS(19), 1,
      anon_sym_mod,
    STATE(2), 7,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_device,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [99] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_PIPE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      sym_value,
    ACTIONS(41), 2,
      anon_sym_COMMA,
      sym_identifier,
    ACTIONS(49), 2,
      sym_string,
      sym_number,
    STATE(9), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [127] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PIPE,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      sym_value,
    ACTIONS(49), 2,
      sym_string,
      sym_number,
    ACTIONS(51), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [152] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      sym_value,
    ACTIONS(49), 2,
      sym_string,
      sym_number,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(6), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [177] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(23), 1,
      sym_value,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
    ACTIONS(63), 3,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
    ACTIONS(65), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [198] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      sym_value,
    ACTIONS(49), 2,
      sym_string,
      sym_number,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [223] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_base_type,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_Optional,
    ACTIONS(74), 1,
      sym_identifier,
    STATE(34), 1,
      sym_type,
    STATE(32), 3,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
  [247] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_base_type,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_Optional,
    ACTIONS(74), 1,
      sym_identifier,
    STATE(86), 1,
      sym_type,
    STATE(32), 3,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
  [271] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_base_type,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_Optional,
    ACTIONS(74), 1,
      sym_identifier,
    STATE(59), 1,
      sym_type,
    STATE(32), 3,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
  [295] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [373] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 6,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_device,
      anon_sym_mod,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 6,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_number,
  [397] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      anon_sym_signal,
    ACTIONS(96), 1,
      sym_identifier,
    STATE(22), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [415] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      anon_sym_signal,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(22), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 6,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_number,
  [445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_signal,
    ACTIONS(96), 1,
      sym_identifier,
    STATE(21), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [460] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    ACTIONS(110), 1,
      sym_identifier,
    STATE(107), 1,
      sym_device_field_name,
    STATE(25), 2,
      sym_device_field,
      aux_sym_device_repeat1,
  [477] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      sym_identifier,
    STATE(107), 1,
      sym_device_field_name,
    STATE(25), 2,
      sym_device_field,
      aux_sym_device_repeat1,
  [494] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(93), 1,
      sym_value,
    ACTIONS(49), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [506] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(35), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [520] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_method,
    STATE(31), 2,
      sym_method,
      aux_sym_service_repeat1,
  [534] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(43), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [548] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      anon_sym_method,
    STATE(31), 2,
      sym_method,
      aux_sym_service_repeat1,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_PIPE,
    ACTIONS(134), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [574] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(138), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [586] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      sym_identifier,
    STATE(36), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [600] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(35), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [614] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(40), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [628] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(41), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [652] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(87), 1,
      sym_value,
    ACTIONS(49), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      sym_identifier,
    STATE(40), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [678] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    ACTIONS(166), 1,
      sym_identifier,
    STATE(41), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [702] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(43), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [716] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(72), 1,
      sym_value,
    ACTIONS(49), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [728] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(113), 1,
      sym_value,
    ACTIONS(49), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [750] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_identifier,
    STATE(107), 1,
      sym_device_field_name,
    STATE(26), 2,
      sym_device_field,
      aux_sym_device_repeat1,
  [764] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [773] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(28), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(30), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [795] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      sym_identifier,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_PIPE,
    ACTIONS(51), 2,
      anon_sym_COMMA,
      sym_identifier,
  [826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_PIPE,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      sym_identifier,
  [837] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(37), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    ACTIONS(188), 2,
      anon_sym_signal,
      sym_identifier,
  [859] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_method,
    STATE(29), 2,
      sym_method,
      aux_sym_service_repeat1,
  [870] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 2,
      anon_sym_signal,
      sym_identifier,
  [881] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACK,
  [891] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_COMMA,
      sym_identifier,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [915] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 2,
      anon_sym_COMMA,
      sym_identifier,
  [931] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(78), 1,
      sym__mod_name,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      sym_identifier,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      sym_identifier,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      anon_sym_RBRACE,
      anon_sym_method,
  [973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_number,
  [988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COMMA,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym_identifier,
  [1002] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_for,
  [1009] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_AT,
  [1016] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LBRACE,
  [1023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_SEMI,
  [1030] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_SEMI,
  [1037] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_identifier,
  [1044] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
  [1051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_identifier,
  [1058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COLON,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_number,
  [1079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_identifier,
  [1086] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_RBRACK,
  [1093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_COMMA,
  [1100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym_identifier,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_COLON,
  [1114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_number,
  [1121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
  [1128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
  [1135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_COMMA,
  [1142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
  [1149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      sym_identifier,
  [1156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_AT,
  [1163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
  [1170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_AT,
  [1177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
  [1184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_EQ,
  [1198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_COLON,
  [1205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
  [1212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_LBRACE,
  [1219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
  [1226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COLON,
  [1233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_COLON,
  [1240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_returns,
  [1247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_string,
  [1254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym_identifier,
  [1261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_LBRACK,
  [1268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      sym_number,
  [1275] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
  [1282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_LBRACE,
  [1289] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_COLON,
  [1296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 127,
  [SMALL_STATE(7)] = 152,
  [SMALL_STATE(8)] = 177,
  [SMALL_STATE(9)] = 198,
  [SMALL_STATE(10)] = 223,
  [SMALL_STATE(11)] = 247,
  [SMALL_STATE(12)] = 271,
  [SMALL_STATE(13)] = 295,
  [SMALL_STATE(14)] = 308,
  [SMALL_STATE(15)] = 321,
  [SMALL_STATE(16)] = 334,
  [SMALL_STATE(17)] = 347,
  [SMALL_STATE(18)] = 360,
  [SMALL_STATE(19)] = 373,
  [SMALL_STATE(20)] = 385,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 415,
  [SMALL_STATE(23)] = 433,
  [SMALL_STATE(24)] = 445,
  [SMALL_STATE(25)] = 460,
  [SMALL_STATE(26)] = 477,
  [SMALL_STATE(27)] = 494,
  [SMALL_STATE(28)] = 506,
  [SMALL_STATE(29)] = 520,
  [SMALL_STATE(30)] = 534,
  [SMALL_STATE(31)] = 548,
  [SMALL_STATE(32)] = 562,
  [SMALL_STATE(33)] = 574,
  [SMALL_STATE(34)] = 586,
  [SMALL_STATE(35)] = 600,
  [SMALL_STATE(36)] = 614,
  [SMALL_STATE(37)] = 628,
  [SMALL_STATE(38)] = 642,
  [SMALL_STATE(39)] = 652,
  [SMALL_STATE(40)] = 664,
  [SMALL_STATE(41)] = 678,
  [SMALL_STATE(42)] = 692,
  [SMALL_STATE(43)] = 702,
  [SMALL_STATE(44)] = 716,
  [SMALL_STATE(45)] = 728,
  [SMALL_STATE(46)] = 738,
  [SMALL_STATE(47)] = 750,
  [SMALL_STATE(48)] = 764,
  [SMALL_STATE(49)] = 773,
  [SMALL_STATE(50)] = 784,
  [SMALL_STATE(51)] = 795,
  [SMALL_STATE(52)] = 806,
  [SMALL_STATE(53)] = 815,
  [SMALL_STATE(54)] = 826,
  [SMALL_STATE(55)] = 837,
  [SMALL_STATE(56)] = 848,
  [SMALL_STATE(57)] = 859,
  [SMALL_STATE(58)] = 870,
  [SMALL_STATE(59)] = 881,
  [SMALL_STATE(60)] = 891,
  [SMALL_STATE(61)] = 899,
  [SMALL_STATE(62)] = 907,
  [SMALL_STATE(63)] = 915,
  [SMALL_STATE(64)] = 923,
  [SMALL_STATE(65)] = 931,
  [SMALL_STATE(66)] = 941,
  [SMALL_STATE(67)] = 949,
  [SMALL_STATE(68)] = 957,
  [SMALL_STATE(69)] = 965,
  [SMALL_STATE(70)] = 973,
  [SMALL_STATE(71)] = 981,
  [SMALL_STATE(72)] = 988,
  [SMALL_STATE(73)] = 995,
  [SMALL_STATE(74)] = 1002,
  [SMALL_STATE(75)] = 1009,
  [SMALL_STATE(76)] = 1016,
  [SMALL_STATE(77)] = 1023,
  [SMALL_STATE(78)] = 1030,
  [SMALL_STATE(79)] = 1037,
  [SMALL_STATE(80)] = 1044,
  [SMALL_STATE(81)] = 1051,
  [SMALL_STATE(82)] = 1058,
  [SMALL_STATE(83)] = 1065,
  [SMALL_STATE(84)] = 1072,
  [SMALL_STATE(85)] = 1079,
  [SMALL_STATE(86)] = 1086,
  [SMALL_STATE(87)] = 1093,
  [SMALL_STATE(88)] = 1100,
  [SMALL_STATE(89)] = 1107,
  [SMALL_STATE(90)] = 1114,
  [SMALL_STATE(91)] = 1121,
  [SMALL_STATE(92)] = 1128,
  [SMALL_STATE(93)] = 1135,
  [SMALL_STATE(94)] = 1142,
  [SMALL_STATE(95)] = 1149,
  [SMALL_STATE(96)] = 1156,
  [SMALL_STATE(97)] = 1163,
  [SMALL_STATE(98)] = 1170,
  [SMALL_STATE(99)] = 1177,
  [SMALL_STATE(100)] = 1184,
  [SMALL_STATE(101)] = 1191,
  [SMALL_STATE(102)] = 1198,
  [SMALL_STATE(103)] = 1205,
  [SMALL_STATE(104)] = 1212,
  [SMALL_STATE(105)] = 1219,
  [SMALL_STATE(106)] = 1226,
  [SMALL_STATE(107)] = 1233,
  [SMALL_STATE(108)] = 1240,
  [SMALL_STATE(109)] = 1247,
  [SMALL_STATE(110)] = 1254,
  [SMALL_STATE(111)] = 1261,
  [SMALL_STATE(112)] = 1268,
  [SMALL_STATE(113)] = 1275,
  [SMALL_STATE(114)] = 1282,
  [SMALL_STATE(115)] = 1289,
  [SMALL_STATE(116)] = 1296,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 8),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 8),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 8),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_block, 5, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod_expr, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 7, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl, 7, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_argument, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_device_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_device_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_array_type, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_signal_block_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_signal_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_type, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_block_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_block_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 6),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 8),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signal_block, 6, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signal_block, 6, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_field, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extension_field, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 7, 0, 7),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_field, 4, 0, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 6, 0, 7),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_field, 4, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 8),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 9, 0, 9),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mod_name, 1, 0, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [270] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_field_name, 1, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fcp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fcp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
