/* Automatically generated by tree-sitter v0.25.2 (6e0618704ad758ba2ea5822faa80bcd36fbeba3d) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 108
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_version = 1,
  anon_sym_COLON = 2,
  anon_sym_struct = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_AT = 6,
  anon_sym_COMMA = 7,
  anon_sym_PIPE = 8,
  sym_base_type = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_Optional = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_enum = 15,
  anon_sym_EQ = 16,
  anon_sym_impl = 17,
  anon_sym_for = 18,
  anon_sym_signal = 19,
  anon_sym_service = 20,
  anon_sym_rpc = 21,
  anon_sym_returns = 22,
  anon_sym_mod = 23,
  anon_sym_SEMI = 24,
  sym_identifier = 25,
  sym_string = 26,
  sym_number = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym_preamble = 30,
  sym_struct = 31,
  sym_struct_name = 32,
  sym_struct_field = 33,
  sym_struct_field_name = 34,
  sym_type = 35,
  sym_array_type = 36,
  sym_dynamic_array_type = 37,
  sym_optional_type = 38,
  sym_composed_type = 39,
  sym_param = 40,
  sym_param_name = 41,
  sym_param_argument = 42,
  sym_enum_block = 43,
  sym_enum_name = 44,
  sym_enum_field = 45,
  sym_enum_field_name = 46,
  sym_impl = 47,
  sym_extension_field = 48,
  sym_signal_block = 49,
  sym_service = 50,
  sym_rpc = 51,
  sym_rpc_name = 52,
  sym_rpc_input_type = 53,
  sym_rpc_output_type = 54,
  sym_mod_expr = 55,
  sym_value = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_struct_repeat1 = 58,
  aux_sym_struct_field_repeat1 = 59,
  aux_sym_param_repeat1 = 60,
  aux_sym_enum_block_repeat1 = 61,
  aux_sym_impl_repeat1 = 62,
  aux_sym_signal_block_repeat1 = 63,
  aux_sym_service_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_version] = "version",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE] = "|",
  [sym_base_type] = "base_type",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_Optional] = "Optional",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_enum] = "enum",
  [anon_sym_EQ] = "=",
  [anon_sym_impl] = "impl",
  [anon_sym_for] = "for",
  [anon_sym_signal] = "signal",
  [anon_sym_service] = "service",
  [anon_sym_rpc] = "rpc",
  [anon_sym_returns] = "returns",
  [anon_sym_mod] = "mod",
  [anon_sym_SEMI] = ";",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_struct] = "struct",
  [sym_struct_name] = "struct_name",
  [sym_struct_field] = "struct_field",
  [sym_struct_field_name] = "struct_field_name",
  [sym_type] = "type",
  [sym_array_type] = "array_type",
  [sym_dynamic_array_type] = "dynamic_array_type",
  [sym_optional_type] = "optional_type",
  [sym_composed_type] = "composed_type",
  [sym_param] = "param",
  [sym_param_name] = "param_name",
  [sym_param_argument] = "param_argument",
  [sym_enum_block] = "enum_block",
  [sym_enum_name] = "enum_name",
  [sym_enum_field] = "enum_field",
  [sym_enum_field_name] = "enum_field_name",
  [sym_impl] = "impl",
  [sym_extension_field] = "extension_field",
  [sym_signal_block] = "signal_block",
  [sym_service] = "service",
  [sym_rpc] = "rpc",
  [sym_rpc_name] = "rpc_name",
  [sym_rpc_input_type] = "rpc_input_type",
  [sym_rpc_output_type] = "rpc_output_type",
  [sym_mod_expr] = "mod_expr",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_struct_field_repeat1] = "struct_field_repeat1",
  [aux_sym_param_repeat1] = "param_repeat1",
  [aux_sym_enum_block_repeat1] = "enum_block_repeat1",
  [aux_sym_impl_repeat1] = "impl_repeat1",
  [aux_sym_signal_block_repeat1] = "signal_block_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_base_type] = sym_base_type,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_Optional] = anon_sym_Optional,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_rpc] = anon_sym_rpc,
  [anon_sym_returns] = anon_sym_returns,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_struct] = sym_struct,
  [sym_struct_name] = sym_struct_name,
  [sym_struct_field] = sym_struct_field,
  [sym_struct_field_name] = sym_struct_field_name,
  [sym_type] = sym_type,
  [sym_array_type] = sym_array_type,
  [sym_dynamic_array_type] = sym_dynamic_array_type,
  [sym_optional_type] = sym_optional_type,
  [sym_composed_type] = sym_composed_type,
  [sym_param] = sym_param,
  [sym_param_name] = sym_param_name,
  [sym_param_argument] = sym_param_argument,
  [sym_enum_block] = sym_enum_block,
  [sym_enum_name] = sym_enum_name,
  [sym_enum_field] = sym_enum_field,
  [sym_enum_field_name] = sym_enum_field_name,
  [sym_impl] = sym_impl,
  [sym_extension_field] = sym_extension_field,
  [sym_signal_block] = sym_signal_block,
  [sym_service] = sym_service,
  [sym_rpc] = sym_rpc,
  [sym_rpc_name] = sym_rpc_name,
  [sym_rpc_input_type] = sym_rpc_input_type,
  [sym_rpc_output_type] = sym_rpc_output_type,
  [sym_mod_expr] = sym_mod_expr,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_struct_field_repeat1] = aux_sym_struct_field_repeat1,
  [aux_sym_param_repeat1] = aux_sym_param_repeat1,
  [aux_sym_enum_block_repeat1] = aux_sym_enum_block_repeat1,
  [aux_sym_impl_repeat1] = aux_sym_impl_repeat1,
  [aux_sym_signal_block_repeat1] = aux_sym_signal_block_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_base_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rpc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_type] = {
    .visible = true,
    .named = true,
  },
  [sym_composed_type] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_param_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_block] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_name] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_field] = {
    .visible = true,
    .named = true,
  },
  [sym_signal_block] = {
    .visible = true,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym_rpc] = {
    .visible = true,
    .named = true,
  },
  [sym_rpc_name] = {
    .visible = true,
    .named = true,
  },
  [sym_rpc_input_type] = {
    .visible = true,
    .named = true,
  },
  [sym_rpc_output_type] = {
    .visible = true,
    .named = true,
  },
  [sym_mod_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_impl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_signal_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 37,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 47,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 99,
  [105] = 105,
  [106] = 97,
  [107] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(64);
      ADVANCE_MAP(
        '"', 9,
        '(', 81,
        ')', 82,
        ',', 71,
        '/', 10,
        ':', 66,
        ';', 93,
        '=', 84,
        '@', 70,
        'O', 45,
        '[', 77,
      );
      if (lookahead == '\\') SKIP(63);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 'm') ADVANCE(42);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == 's') ADVANCE(26);
      if (lookahead == 'u') ADVANCE(61);
      if (lookahead == 'v') ADVANCE(27);
      if (lookahead == '{') ADVANCE(68);
      if (lookahead == '|') ADVANCE(72);
      if (lookahead == '}') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(14);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\r') ADVANCE(116);
      if (lookahead == '\\') ADVANCE(114);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '(') ADVANCE(81);
      if (lookahead == ')') ADVANCE(82);
      if (lookahead == ',') ADVANCE(71);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') SKIP(2);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '|') ADVANCE(72);
      if (lookahead == '}') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(115);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(113);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == 'O') ADVANCE(107);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == 'f') ADVANCE(95);
      if (lookahead == 'i') ADVANCE(109);
      if (lookahead == 'u') ADVANCE(109);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') SKIP(6);
      if (lookahead == 's') ADVANCE(101);
      if (lookahead == '}') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 15:
      if (lookahead == '2') ADVANCE(73);
      END_STATE();
    case 16:
      if (lookahead == '3') ADVANCE(15);
      if (lookahead == '6') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == '4') ADVANCE(73);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(90);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(83);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(54);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 52:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 59:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 60:
      if (lookahead == 'v') ADVANCE(31);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 62:
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 63:
      if (eof) ADVANCE(64);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_base_type);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_base_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_Optional);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_Optional);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_signal);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_signal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_rpc);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(94);
      if (lookahead == '6') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(116);
      if (lookahead == '\\') ADVANCE(114);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 8},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 8},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 8},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 8},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 8},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_base_type] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_Optional] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_rpc] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(98),
    [sym_preamble] = STATE(4),
    [anon_sym_version] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_service,
    ACTIONS(17), 1,
      anon_sym_mod,
    STATE(3), 6,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [30] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_struct,
    ACTIONS(24), 1,
      anon_sym_enum,
    ACTIONS(27), 1,
      anon_sym_impl,
    ACTIONS(30), 1,
      anon_sym_service,
    ACTIONS(33), 1,
      anon_sym_mod,
    STATE(3), 6,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [60] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_impl,
    ACTIONS(15), 1,
      anon_sym_service,
    ACTIONS(17), 1,
      anon_sym_mod,
    STATE(2), 6,
      sym_struct,
      sym_enum_block,
      sym_impl,
      sym_service,
      sym_mod_expr,
      aux_sym_source_file_repeat1,
  [87] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_PIPE,
    ACTIONS(40), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_value,
    ACTIONS(36), 2,
      anon_sym_COMMA,
      sym_identifier,
    ACTIONS(44), 2,
      sym_string,
      sym_number,
    STATE(6), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [115] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_PIPE,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_value,
    ACTIONS(44), 2,
      sym_string,
      sym_number,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [140] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym_base_type,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_Optional,
    ACTIONS(58), 1,
      sym_identifier,
    STATE(28), 1,
      sym_type,
    STATE(34), 4,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
      sym_composed_type,
  [165] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(21), 1,
      sym_value,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
    ACTIONS(60), 3,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
    ACTIONS(62), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [186] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_PIPE,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_value,
    ACTIONS(44), 2,
      sym_string,
      sym_number,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(12), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [211] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym_base_type,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_Optional,
    ACTIONS(58), 1,
      sym_identifier,
    STATE(56), 1,
      sym_type,
    STATE(34), 4,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
      sym_composed_type,
  [236] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym_base_type,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_Optional,
    ACTIONS(58), 1,
      sym_identifier,
    STATE(80), 1,
      sym_type,
    STATE(34), 4,
      sym_array_type,
      sym_dynamic_array_type,
      sym_optional_type,
      sym_composed_type,
  [261] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_value,
    ACTIONS(44), 2,
      sym_string,
      sym_number,
    ACTIONS(65), 2,
      anon_sym_COMMA,
      sym_identifier,
    STATE(8), 2,
      sym_param_argument,
      aux_sym_param_repeat1,
  [286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 7,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_number,
  [299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [311] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 6,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_number,
  [359] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      anon_sym_signal,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(22), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 6,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_number,
  [401] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_signal,
    ACTIONS(98), 1,
      sym_identifier,
    STATE(22), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [419] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(81), 1,
      sym_struct_field_name,
    STATE(27), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [436] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(94), 1,
      sym_enum_field_name,
    STATE(25), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [453] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(111), 1,
      sym_identifier,
    STATE(94), 1,
      sym_enum_field_name,
    STATE(25), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [470] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_signal,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(19), 3,
      sym_extension_field,
      sym_signal_block,
      aux_sym_impl_repeat1,
  [485] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(116), 1,
      sym_identifier,
    STATE(81), 1,
      sym_struct_field_name,
    STATE(27), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [502] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      sym_identifier,
    STATE(5), 1,
      sym_param_name,
    STATE(29), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [519] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(5), 1,
      sym_param_name,
    STATE(31), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 5,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_impl,
      anon_sym_service,
      anon_sym_mod,
  [547] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(5), 1,
      sym_param_name,
    STATE(31), 2,
      sym_param,
      aux_sym_struct_field_repeat1,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(81), 1,
      sym_struct_field_name,
    STATE(23), 2,
      sym_struct_field,
      aux_sym_struct_repeat1,
  [578] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(95), 1,
      sym_value,
    ACTIONS(44), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_PIPE,
    ACTIONS(132), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [602] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 1,
      anon_sym_rpc,
    STATE(35), 2,
      sym_rpc,
      aux_sym_service_repeat1,
  [616] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(41), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [630] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(99), 1,
      sym_value,
    ACTIONS(44), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [662] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(94), 1,
      sym_enum_field_name,
    STATE(24), 2,
      sym_enum_field,
      aux_sym_enum_block_repeat1,
  [676] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(41), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [700] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    ACTIONS(158), 1,
      anon_sym_rpc,
    STATE(35), 2,
      sym_rpc,
      aux_sym_service_repeat1,
  [714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [724] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(104), 1,
      sym_value,
    ACTIONS(44), 3,
      sym_identifier,
      sym_string,
      sym_number,
  [736] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      sym_identifier,
  [747] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 2,
      anon_sym_signal,
      sym_identifier,
  [758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_rpc,
    STATE(43), 2,
      sym_rpc,
      aux_sym_service_repeat1,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(36), 2,
      sym_extension_field,
      aux_sym_signal_block_repeat1,
  [780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    ACTIONS(170), 2,
      anon_sym_signal,
      sym_identifier,
  [800] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(65), 2,
      anon_sym_COMMA,
      sym_identifier,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      sym_identifier,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_COMMA,
      sym_identifier,
  [830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [838] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
  [848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(85), 1,
      sym_rpc_name,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(63), 1,
      sym_rpc_output_type,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      sym_identifier,
  [884] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_RBRACE,
      anon_sym_rpc,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      anon_sym_rpc,
  [908] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_identifier,
    STATE(75), 1,
      sym_struct_name,
  [918] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(79), 1,
      sym_enum_name,
  [928] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(77), 1,
      sym_rpc_input_type,
  [938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      sym_identifier,
  [946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_COMMA,
      sym_identifier,
  [954] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_number,
  [969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_COLON,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_number,
  [990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LBRACE,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACK,
  [1039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_AT,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_for,
  [1053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
  [1060] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
  [1067] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identifier,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_SEMI,
  [1088] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_COMMA,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_string,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_LBRACK,
  [1109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_EQ,
  [1116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
  [1123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_COLON,
  [1130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_EQ,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
  [1144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_COLON,
  [1158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
  [1172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_returns,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_identifier,
  [1200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_AT,
  [1214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_COLON,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 165,
  [SMALL_STATE(9)] = 186,
  [SMALL_STATE(10)] = 211,
  [SMALL_STATE(11)] = 236,
  [SMALL_STATE(12)] = 261,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 311,
  [SMALL_STATE(16)] = 323,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 347,
  [SMALL_STATE(19)] = 359,
  [SMALL_STATE(20)] = 377,
  [SMALL_STATE(21)] = 389,
  [SMALL_STATE(22)] = 401,
  [SMALL_STATE(23)] = 419,
  [SMALL_STATE(24)] = 436,
  [SMALL_STATE(25)] = 453,
  [SMALL_STATE(26)] = 470,
  [SMALL_STATE(27)] = 485,
  [SMALL_STATE(28)] = 502,
  [SMALL_STATE(29)] = 519,
  [SMALL_STATE(30)] = 536,
  [SMALL_STATE(31)] = 547,
  [SMALL_STATE(32)] = 564,
  [SMALL_STATE(33)] = 578,
  [SMALL_STATE(34)] = 590,
  [SMALL_STATE(35)] = 602,
  [SMALL_STATE(36)] = 616,
  [SMALL_STATE(37)] = 630,
  [SMALL_STATE(38)] = 642,
  [SMALL_STATE(39)] = 652,
  [SMALL_STATE(40)] = 662,
  [SMALL_STATE(41)] = 676,
  [SMALL_STATE(42)] = 690,
  [SMALL_STATE(43)] = 700,
  [SMALL_STATE(44)] = 714,
  [SMALL_STATE(45)] = 724,
  [SMALL_STATE(46)] = 736,
  [SMALL_STATE(47)] = 747,
  [SMALL_STATE(48)] = 758,
  [SMALL_STATE(49)] = 769,
  [SMALL_STATE(50)] = 780,
  [SMALL_STATE(51)] = 789,
  [SMALL_STATE(52)] = 800,
  [SMALL_STATE(53)] = 811,
  [SMALL_STATE(54)] = 822,
  [SMALL_STATE(55)] = 830,
  [SMALL_STATE(56)] = 838,
  [SMALL_STATE(57)] = 848,
  [SMALL_STATE(58)] = 858,
  [SMALL_STATE(59)] = 866,
  [SMALL_STATE(60)] = 876,
  [SMALL_STATE(61)] = 884,
  [SMALL_STATE(62)] = 892,
  [SMALL_STATE(63)] = 900,
  [SMALL_STATE(64)] = 908,
  [SMALL_STATE(65)] = 918,
  [SMALL_STATE(66)] = 928,
  [SMALL_STATE(67)] = 938,
  [SMALL_STATE(68)] = 946,
  [SMALL_STATE(69)] = 954,
  [SMALL_STATE(70)] = 962,
  [SMALL_STATE(71)] = 969,
  [SMALL_STATE(72)] = 976,
  [SMALL_STATE(73)] = 983,
  [SMALL_STATE(74)] = 990,
  [SMALL_STATE(75)] = 997,
  [SMALL_STATE(76)] = 1004,
  [SMALL_STATE(77)] = 1011,
  [SMALL_STATE(78)] = 1018,
  [SMALL_STATE(79)] = 1025,
  [SMALL_STATE(80)] = 1032,
  [SMALL_STATE(81)] = 1039,
  [SMALL_STATE(82)] = 1046,
  [SMALL_STATE(83)] = 1053,
  [SMALL_STATE(84)] = 1060,
  [SMALL_STATE(85)] = 1067,
  [SMALL_STATE(86)] = 1074,
  [SMALL_STATE(87)] = 1081,
  [SMALL_STATE(88)] = 1088,
  [SMALL_STATE(89)] = 1095,
  [SMALL_STATE(90)] = 1102,
  [SMALL_STATE(91)] = 1109,
  [SMALL_STATE(92)] = 1116,
  [SMALL_STATE(93)] = 1123,
  [SMALL_STATE(94)] = 1130,
  [SMALL_STATE(95)] = 1137,
  [SMALL_STATE(96)] = 1144,
  [SMALL_STATE(97)] = 1151,
  [SMALL_STATE(98)] = 1158,
  [SMALL_STATE(99)] = 1165,
  [SMALL_STATE(100)] = 1172,
  [SMALL_STATE(101)] = 1179,
  [SMALL_STATE(102)] = 1186,
  [SMALL_STATE(103)] = 1193,
  [SMALL_STATE(104)] = 1200,
  [SMALL_STATE(105)] = 1207,
  [SMALL_STATE(106)] = 1214,
  [SMALL_STATE(107)] = 1221,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod_expr, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_block, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl, 7, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_argument, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_impl_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_block_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_block_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_array_type, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composed_type, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_signal_block_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_signal_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_type, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_field, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extension_field, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signal_block, 6, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signal_block, 6, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_field, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 6, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 7, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpc_output_type, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpc, 7, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpc_input_type, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_name, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rpc_name, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_field_name, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field_name, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fcp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fcp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
