#!/usr/bin/env python3

import sys
import os

def main(args):
    with open("fcp/version.py") as f:
        txt = f.read()
        version = txt.split("=")[1].strip()
        version = "v"+version[1:-1]+".md"

    if version in os.listdir("public"):
        exit(0)
    else:
        print(f"[check_release_notes]: No release note found for: {version}")
        exit(1)

if __name__ == '__main__':
    main(sys.argv)
