#include "ecu_rpc_client.h"
#include "generated_code/ecu_rpc.h"
#include "generated_code/ecu_can.h"

#include <string.h>
#include <stdbool.h>

/*---------------------------------------- Internal Utilities --------------------------------------*/
static CanFrame rpc_response;

static void capture_response(const CanFrame *frame) {
    if (frame) rpc_response = *frame;
}

/*---------------------------------------- RPC Client Functions ------------------------------------*/

bool sensorservice_request_state(uint8_t *result) {
    if (!result) return false;

    CanRpcSensorReq request = {
        .request_id = 0x01
    };

    CanFrame frame = can_encode_rpc_sensor_req(&request);

    // Send and process locally through dispatch
    ecu_service_dispatch(&frame, capture_response);

    // Decode response
    CanRpcSensorInformation response = can_decode_rpc_sensor_information(&rpc_response);
    *result = response.result;

    return true;
}

/*---------------------------------------- Service Handlers ----------------------------------------*/

// SENSOR.REQUEST_STATE
void ecu_service_handle_request_state(const CanFrame *req, CanFrame *resp) {
    if (!req || !resp) return;

    CanRpcSensorReq request = can_decode_rpc_sensor_req(req);
    CanRpcSensorInformation response = {0};

    switch (request.request_id) {
        case 0x01: response.result = 0xA0; break;
        case 0x02: response.result = 0xB0; break;
        case 0x11: response.result = 0xCD; break;
        default:   response.result = 0xFF; break;
    }

    *resp = can_encode_rpc_sensor_information(&response);
    resp->id = ECU_RPC_ANS_ID;
}

// SENSOR.GET_TEMPERATURE
void ecu_service_handle_get_temperature(const CanFrame *req, CanFrame *resp) {
    if (!req || !resp) return;

    CanRpcSensorReq request = can_decode_rpc_sensor_req(req);
    CanRpcTemperatureResponse response = {0};

    switch (request.request_id) {
        case 0x01: response.result = 22; break;
        case 0x02: response.result = 28; break;
        default:   response.result = 0xFF; break;
    }

    *resp = can_encode_rpc_temperature_response(&response);
    resp->id = ECU_RPC_ANS_ID;
}

/*---------------------------------------- RPC Registration ----------------------------------------*/

/**
 * @brief Initialize and register all ECU RPC handlers dynamically.
 * 
 * This replaces the old static handler table and allows modular updates.
 */
void ecu_rpc_client_init(void) {
    ecu_rpc_init(); // optional: pre-registers all autogenerated handlers if any

    // Register service handlers dynamically
    ecu_rpc_register(0, 0, ecu_service_handle_request_state);
    ecu_rpc_register(0, 1, ecu_service_handle_get_temperature);
}
